server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/article?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB     # 设置最大上传文件大小为10MB
      max-request-size: 10MB  # 设置请求最大大小为10MB
      location: ./resource/image   # 设置文件上传的临时目录，这里是在/tmp/upload下

mybatis:
  type-aliases-package: com.example.newDemo.bean